[package]
name = "db_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["rt", "sync"] }
surrealdb = { version = "1", features = ["kv-mem"] }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
chrono =  "0.4"